# Yocto layer for Power Window
#
# Provides all needed to build a bootable image
#   - Machine config and SoC-family include
#   - Kernel recipe
#   - U-Boot recipe + rkbin prprietary blobs
#   - WIC partition layout + extlinux config
#   - Distro config (DISTRO = "power-window-os")
#   - Image recipe (power-window-image)
#   - Power Window app

BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "power-window"
BBFILE_PATTERN_power-window = "^${LAYERDIR}/"
BBFILE_PRIORITY_power-window = "10"

LAYERDEPENDS_power-window = "core qt5-layer"
LAYERSERIES_COMPAT_power-window = "scarthgap"